server:
  port: 8000

eureka:
  instance:
    hostname: gateway.studio.i
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.78.155.253:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: api
          uri: lb://api
          predicates:
            - Path=/api/**


