server:
  port: 8000

eureka:
  instance:
    hostname : 13.125.181.139
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.78.155.253:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: api
          uri: lb://API
          predicates:
            - Path=/api/**