server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.78.155.253:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: api
          uri: lb://api
          predicates:
            - Path=/api/**


